table Prefinal
	lineageTag: 5ab99e05-2f69-4b04-b53e-c79376ab0c6e

	column 'Source.Name'
		dataType: string
		lineageTag: 56815841-19ae-45ba-90b4-e337c2cdfff4
		summarizeBy: none
		sourceColumn: Source.Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: d669e3c7-8be9-4737-b524-95c135475467
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5b777ec9-b8ba-4b85-9559-2e1d37446f7e
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: fe46c384-bf18-4b36-9251-ee286e75927b
			defaultHierarchy: LocalDateTable_66a95c58-38e7-4d13-8f64-8709bf46dc33.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Inspection Stage'
		dataType: string
		lineageTag: 9fa942d3-a676-4e6d-9b5c-0574b89ab876
		summarizeBy: none
		sourceColumn: Inspection Stage

		annotation SummarizationSetBy = Automatic

	column Factory
		dataType: string
		lineageTag: 01c00e1a-5a16-49ba-b5ba-daab4958e618
		summarizeBy: none
		sourceColumn: Factory

		annotation SummarizationSetBy = Automatic

	column Building
		dataType: string
		lineageTag: c3db1c2f-292c-43d7-9c9b-f143fb291d3c
		summarizeBy: none
		sourceColumn: Building

		annotation SummarizationSetBy = Automatic

	column Floor
		dataType: string
		lineageTag: ace578b4-f4ec-4d5c-b917-8429994017f3
		summarizeBy: none
		sourceColumn: Floor

		annotation SummarizationSetBy = Automatic

	column 'Line No'
		dataType: string
		lineageTag: 11fde210-73ef-4c9d-8bc1-ba99e7451af6
		summarizeBy: none
		sourceColumn: Line No

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: 46835a12-1f84-4dc0-abb6-0edfe1e5392d
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Buyer
		dataType: string
		lineageTag: 15544ae7-3bc8-4287-9a46-fa9d1c9007f6
		summarizeBy: none
		sourceColumn: Buyer

		annotation SummarizationSetBy = Automatic

	column Style
		dataType: string
		lineageTag: 7c28ab29-0d46-4117-8d3e-dfdbb718ad8b
		summarizeBy: none
		sourceColumn: Style

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: d870971b-1e90-45e6-80c3-06a90480b117
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column MO
		dataType: string
		lineageTag: f4a25128-67d0-47c5-be0e-36e671dab557
		summarizeBy: none
		sourceColumn: MO

		annotation SummarizationSetBy = Automatic

	column 'Operation Name'
		dataType: string
		lineageTag: be2c1b93-bf13-44cb-95ff-2d57dc80cfdd
		summarizeBy: none
		sourceColumn: Operation Name

		annotation SummarizationSetBy = Automatic

	column OperatorsID
		dataType: string
		lineageTag: c5d18a8b-67b4-446c-9656-9c53efc40d55
		summarizeBy: none
		sourceColumn: OperatorsID

		annotation SummarizationSetBy = Automatic

	column InspectorName
		dataType: string
		lineageTag: 94bfb27f-2bb6-4ed7-87a8-d3808ec17897
		summarizeBy: none
		sourceColumn: InspectorName

		annotation SummarizationSetBy = Automatic

	column 'Inspectors ID'
		dataType: string
		lineageTag: 581d3b83-e570-40de-8ffb-bdd92479f890
		summarizeBy: none
		sourceColumn: Inspectors ID

		annotation SummarizationSetBy = Automatic

	column 'Total Check Quantity'
		dataType: int64
		formatString: 0
		lineageTag: e30f70b0-7b06-46b1-bdc6-d1f4f416fb42
		summarizeBy: sum
		sourceColumn: Total Check Quantity

		annotation SummarizationSetBy = Automatic

	column 'Improper SPI/width stitches'
		dataType: int64
		formatString: 0
		lineageTag: ab5dc181-d352-4b1a-9586-37a558a97dc5
		summarizeBy: sum
		sourceColumn: Improper SPI/width stitches

		annotation SummarizationSetBy = Automatic

	column 'Skip stitches'
		dataType: int64
		formatString: 0
		lineageTag: 24fa5032-5baf-4bed-a74f-8840c80d4d69
		summarizeBy: sum
		sourceColumn: Skip stitches

		annotation SummarizationSetBy = Automatic

	column 'Stitch Tension Tight / Loose /Cracking '
		dataType: int64
		formatString: 0
		lineageTag: a66d3c8b-0417-4a0d-a2fd-c099295bb696
		summarizeBy: sum
		sourceColumn: "Stitch Tension Tight / Loose /Cracking "

		annotation SummarizationSetBy = Automatic

	column 'Broken Stitch'
		dataType: int64
		formatString: 0
		lineageTag: b001cc46-d18f-4f3f-bc48-6a1937f964aa
		summarizeBy: sum
		sourceColumn: Broken Stitch

		annotation SummarizationSetBy = Automatic

	column 'Open Seam'
		dataType: int64
		formatString: 0
		lineageTag: d1101ab9-2d86-43f4-912c-d12cdf5a984e
		summarizeBy: sum
		sourceColumn: Open Seam

		annotation SummarizationSetBy = Automatic

	column 'Poor/ join stitch'
		dataType: int64
		formatString: 0
		lineageTag: d5de2651-95a3-4351-be86-cbada26a32f6
		summarizeBy: sum
		sourceColumn: Poor/ join stitch

		annotation SummarizationSetBy = Automatic

	column 'Cup Loose/Tight'
		dataType: int64
		formatString: 0
		lineageTag: 30f826bd-908d-4461-9d04-faa9cf13a4c0
		summarizeBy: sum
		sourceColumn: Cup Loose/Tight

		annotation SummarizationSetBy = Automatic

	column Puckering/Twisted/Wavy
		dataType: int64
		formatString: 0
		lineageTag: bb839afd-f379-4760-b8a2-230d0434b419
		summarizeBy: sum
		sourceColumn: Puckering/Twisted/Wavy

		annotation SummarizationSetBy = Automatic

	column 'High-Low/ asymmetry'
		dataType: int64
		formatString: 0
		lineageTag: 8271e009-da3f-4239-bea5-84d3c8cc8999
		summarizeBy: sum
		sourceColumn: High-Low/ asymmetry

		annotation SummarizationSetBy = Automatic

	column 'Poor/Out of Shape/ Centre Front/Gore out of shape/Slanted'
		dataType: int64
		formatString: 0
		lineageTag: 68018620-41bc-42a3-b0f6-a659abda8076
		summarizeBy: sum
		sourceColumn: Poor/Out of Shape/ Centre Front/Gore out of shape/Slanted

		annotation SummarizationSetBy = Automatic

	column 'Flipping up/Curling down'
		dataType: int64
		formatString: 0
		lineageTag: 8f216a05-05d5-4f29-a9fc-b423b24da685
		summarizeBy: sum
		sourceColumn: Flipping up/Curling down

		annotation SummarizationSetBy = Automatic

	column 'Uneven shearing /Gap/ Gathering'
		dataType: int64
		formatString: 0
		lineageTag: 6f11d9c4-b455-46d1-935c-28448f4b297c
		summarizeBy: sum
		sourceColumn: Uneven shearing /Gap/ Gathering

		annotation SummarizationSetBy = Automatic

	column 'Pointy/ Uneven Seam Allowance/Pleat'
		dataType: int64
		formatString: 0
		lineageTag: b6b85752-4081-45cd-951d-ba13236c0310
		summarizeBy: sum
		sourceColumn: Pointy/ Uneven Seam Allowance/Pleat

		annotation SummarizationSetBy = Automatic

	column 'Measurement (+/-)'
		dataType: int64
		formatString: 0
		lineageTag: 682f4837-903d-4a03-9d55-fe2ea214d677
		summarizeBy: sum
		sourceColumn: Measurement (+/-)

		annotation SummarizationSetBy = Automatic

	column 'Wire Play +/-'
		dataType: int64
		formatString: 0
		lineageTag: 30b953d6-e611-4d43-9cf2-17471317cbcd
		summarizeBy: sum
		sourceColumn: Wire Play +/-

		annotation SummarizationSetBy = Automatic

	column 'Raw edge/ Exposed'
		dataType: int64
		formatString: 0
		lineageTag: 1988a3cf-f86d-41b8-827b-607ef5e702b4
		summarizeBy: sum
		sourceColumn: Raw edge/ Exposed

		annotation SummarizationSetBy = Automatic

	column 'Uncut/Loose Thread '
		dataType: int64
		formatString: 0
		lineageTag: 36a5d622-df36-4c5d-8c31-891df76772d2
		summarizeBy: sum
		sourceColumn: "Uncut/Loose Thread "

		annotation SummarizationSetBy = Automatic

	column 'Crease Mark'
		dataType: int64
		formatString: 0
		lineageTag: cd7b58a8-1324-4554-82ab-cebf0aebf4b1
		summarizeBy: sum
		sourceColumn: Crease Mark

		annotation SummarizationSetBy = Automatic

	column 'Dirty/ Chalk/ pen mark'
		dataType: int64
		formatString: 0
		lineageTag: 91122e2e-cdf2-4899-b583-8814c102ad58
		summarizeBy: sum
		sourceColumn: Dirty/ Chalk/ pen mark

		annotation SummarizationSetBy = Automatic

	column 'Oil /Stain Mark '
		dataType: int64
		formatString: 0
		lineageTag: 008fafa3-1ced-4b77-8032-f86215604335
		summarizeBy: sum
		sourceColumn: "Oil /Stain Mark "

		annotation SummarizationSetBy = Automatic

	column 'Hole/Needle hole/Cut'
		dataType: int64
		formatString: 0
		lineageTag: 3ee424d7-e71a-423a-9ef4-1b3dd06fc0ba
		summarizeBy: sum
		sourceColumn: Hole/Needle hole/Cut

		annotation SummarizationSetBy = Automatic

	column Snagging/Fraying
		dataType: int64
		formatString: 0
		lineageTag: f2259ba4-cb95-413c-9eb1-f400cbc17796
		summarizeBy: sum
		sourceColumn: Snagging/Fraying

		annotation SummarizationSetBy = Automatic

	column 'Bartack Missing/ Improper Bartack'
		dataType: int64
		formatString: 0
		lineageTag: 15c88724-c230-4695-8eac-fc1e8600d8e0
		summarizeBy: sum
		sourceColumn: Bartack Missing/ Improper Bartack

		annotation SummarizationSetBy = Automatic

	column 'Trim/ Label Missing/ Label Not Readable'
		dataType: int64
		formatString: 0
		lineageTag: 7f2accab-4482-4090-b2cc-16be76c6b93a
		summarizeBy: sum
		sourceColumn: Trim/ Label Missing/ Label Not Readable

		annotation SummarizationSetBy = Automatic

	column 'Trim Improperly attached'
		dataType: int64
		formatString: 0
		lineageTag: b66a36e0-5bb4-4974-97df-699dc11515b7
		summarizeBy: sum
		sourceColumn: Trim Improperly attached

		annotation SummarizationSetBy = Automatic

	column 'Sharp Edge'
		dataType: int64
		formatString: 0
		lineageTag: 44a5504f-af7a-4be9-b3ed-fe071ff74492
		summarizeBy: sum
		sourceColumn: Sharp Edge

		annotation SummarizationSetBy = Automatic

	column 'Shade Variation '
		dataType: int64
		formatString: 0
		lineageTag: b2977d52-b230-4c96-8af3-669b8abe6bb8
		summarizeBy: sum
		sourceColumn: "Shade Variation "

		annotation SummarizationSetBy = Automatic

	column 'Straps Insecure/Misplaced/Uneven/Twisted'
		dataType: int64
		formatString: 0
		lineageTag: 31b4bb85-fe86-4f53-8d4b-c03e5005da11
		summarizeBy: sum
		sourceColumn: Straps Insecure/Misplaced/Uneven/Twisted

		annotation SummarizationSetBy = Automatic

	column 'Wrong/ Incorrect Size'
		dataType: int64
		formatString: 0
		lineageTag: ef32dc7d-c7ba-4f7b-af59-948b179eb8f3
		summarizeBy: sum
		sourceColumn: Wrong/ Incorrect Size

		annotation SummarizationSetBy = Automatic

	column 'Other defects'
		dataType: int64
		formatString: 0
		lineageTag: 8c33b801-b302-4f52-94e5-663ff607f0ef
		summarizeBy: sum
		sourceColumn: Other defects

		annotation SummarizationSetBy = Automatic

	column 'Total Defect'
		dataType: int64
		formatString: 0
		lineageTag: f09e8009-cb58-4970-a3ae-7d20c3c918f2
		summarizeBy: sum
		sourceColumn: Total Defect

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 9ec23aa0-5373-44ef-8ea4-77c059159c79
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 49735393-9383-4cb1-bf27-b920eda5c5d0
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 0d561c11-9254-4906-b6e1-4740e9db755c
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 6b852c93-3f0f-463f-9917-6268cd6f136d
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column DHU%
		dataType: string
		lineageTag: af6ed104-8941-4bfe-b1c9-1ec3cbc4e87a
		summarizeBy: none
		sourceColumn: DHU%

		annotation SummarizationSetBy = Automatic

	column RFT%
		dataType: string
		lineageTag: 29038f9a-b626-4d35-a5f9-3cde4a3d223b
		summarizeBy: none
		sourceColumn: RFT%

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: string
		lineageTag: b297a35c-b8f2-4347-9fb3-116f6cfd6fa3
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Reject
		dataType: string
		lineageTag: 511b4477-37b9-4b3b-a0be-6ca5cea0b3d7
		summarizeBy: none
		sourceColumn: Reject

		annotation SummarizationSetBy = Automatic

	column 'Order Qty'
		dataType: string
		lineageTag: 938c2ccc-f242-41e2-b75c-3d90e0c51404
		summarizeBy: none
		sourceColumn: Order Qty

		annotation SummarizationSetBy = Automatic

	column PID
		dataType: string
		lineageTag: e82a2ab8-c576-4241-8885-d06fd8d0593c
		summarizeBy: none
		sourceColumn: PID

		annotation SummarizationSetBy = Automatic

	column 'Tracking No'
		dataType: string
		lineageTag: 0117db86-1419-4371-9840-d2303bbf6d75
		summarizeBy: none
		sourceColumn: Tracking No

		annotation SummarizationSetBy = Automatic

	partition Prefinal = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\mohaimin.chowdhury\OneDrive - Hop Lun\Personal Project - Transformation\Database\Monthly Database\Prefinal"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (3)", each #"Transform File (3)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (3)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (3)", Table.ColumnNames(#"Transform File (3)"(#"Sample File (3)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"Month", type text}, {"Date", type date}, {"Inspection Stage", type text}, {"Factory", type text}, {"Building", type text}, {"Floor", type text}, {"Line #(lf)No", type text}, {"Item", type text}, {"Buyer", type text}, {"Style", type text}, {"Color", type text}, {"MO", type text}, {"Operation #(lf)Name", type text}, {"Operators#(lf)ID", type text}, {"Inspector#(lf)Name", type text}, {"Inspectors ID", type text}, {"Total Check Quantity", Int64.Type}, {"Improper SPI/width stitches#(lf)", Int64.Type}, {"Skip stitches#(lf)", Int64.Type}, {"Stitch Tension Tight / Loose /Cracking #(lf)", Int64.Type}, {"Broken Stitch#(lf)", Int64.Type}, {"Open Seam#(lf)", Int64.Type}, {"Poor/ join stitch#(lf)", Int64.Type}, {"Cup Loose/Tight#(lf)", Int64.Type}, {"Puckering/Twisted/Wavy", Int64.Type}, {"High-Low/ asymmetry#(lf)", Int64.Type}, {"Poor/Out of Shape/ Centre Front/Gore out of shape/Slanted#(lf)", Int64.Type}, {"Flipping up/Curling down", Int64.Type}, {"Uneven shearing /Gap/ Gathering", Int64.Type}, {"Pointy/ Uneven Seam Allowance/Pleat", Int64.Type}, {"Measurement (+/-)#(lf)", Int64.Type}, {"Wire Play +/-", Int64.Type}, {"Raw edge/ Exposed#(lf)", Int64.Type}, {"Uncut/Loose Thread #(lf)", Int64.Type}, {"Crease Mark#(lf)", Int64.Type}, {"Dirty/ Chalk/ pen mark#(lf)", Int64.Type}, {"Oil /Stain Mark #(lf)", Int64.Type}, {"Hole/Needle hole/Cut#(lf)", Int64.Type}, {"Snagging/Fraying#(lf)", Int64.Type}, {"Bartack Missing/ Improper Bartack", Int64.Type}, {"Trim/ Label Missing/ Label Not Readable", Int64.Type}, {"Trim Improperly attached", Int64.Type}, {"Sharp Edge#(lf)", Int64.Type}, {"Shade Variation #(lf)", Int64.Type}, {"Straps Insecure/Misplaced/Uneven/Twisted", Int64.Type}, {"Wrong/ Incorrect Size", Int64.Type}, {"Other defects", Int64.Type}, {"Total Defect", Int64.Type}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"DHU%", type any}, {"RFT%", type any}, {"Index", type text}, {"Reject", type any}, {"Order Qty", type any}, {"PID", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Tracking No", each Date.ToText([Date],"dd-MM-yyyy")&"-"&[Inspection Stage]&"-"&[Factory]&"-"&[Index]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Tracking No", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"Source.Name"})
				in
				    #"Removed Errors"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

